### PR TITLE
elm version

### PR DESCRIPTION
**Pull request by sturgman**
Surely you mean elm >= 0.19? Right?

Also, I am eager to try it out. I have been writing a web-book with org-mode and included a bunch of `Browser.element`s.

### CODE REVIEW

**Review by BonfaceKilz — APPROVED** [review]
Thanks! That never occurred to me :+1:

**Comment by BonfaceKilz** [comment]
:+1: on the book. That would be really great and useful. How's the
plugin going on for you? We could carry this conversation over on
e-mail. Wdyt?

-- 
Bonface M. K.
One Divine Emacs To Rule Them All
https://www.bonfacemunyoki.com

**Comment by sturgman** [comment]
Sure! How do we do that? Couldn't see your email address.

-s-

**Comment by BonfaceKilz** [comment]
It's: bonfacemunyoki@gmail.com

-- 
Bonface M. K.
One Divine Emacs To Rule Them All
https://www.bonfacemunyoki.com

**Pull request merged**
